import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/app-sidebar"
import PrivyProvider from "@/components/providers/privy-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <PrivyProvider>
          <div className="flex flex-col md:flex-row h-screen w-full bg-black overflow-hidden relative">
            <AppSidebar />
            <main className="flex-1 flex flex-col min-h-0 relative z-10 w-full">
              {children}
            </main>
          </div>
        </PrivyProvider>
      </body>
    </html>
  );
}
