import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import PrivyProvider from "@/components/providers/privy-provider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <PrivyProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarInset>
              <main className="relative flex-1 flex flex-col min-w-0">
                <div className="absolute top-4 left-4 z-50">
                  <SidebarTrigger />
                </div>
                {children}
              </main>
            </SidebarInset>
          </SidebarProvider>
        </PrivyProvider>
      </body>
    </html>
  );
}
